---
- hosts: webservers
  user: root
  sudo: yes
  vars: 
    hadoop_home: /home/hadoop/hadoop-2.6.0
  tasks:
  - name: Delete Hadoop Folder
    shell: rm -rf /home/hadoop/hadoop-2.6.0
    ignore_errors: yes
  - name: Download Hadoop
    unarchive: src=/home/EMR/ansible/ansible-repo/hadoop-2.6.0.tar.gz dest=/home/hadoop/.
 
  - name: Edit barc
    lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export HADOOP_HOME=/home/hadoop/hadoop-2.6.0"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export JAVA_HOME=/usr/java/jdk1.8.0_40"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export HADOOP_INSTALL=$HADOOP_HOME"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export HADOOP_MAPRED_HOME=$HADOOP_HOME"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export HADOOP_COMMON_HOME=$HADOOP_HOME"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export HADOOP_HDFS_HOME=$HADOOP_HOME"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export YARN_HOME=$HADOOP_HOME"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native"
  - lineinfile: dest=/home/hadoop/.bashrc regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin"
  
  - name: Appling changes in current run enviroment
    shell: source /home/hadoop/.bashrc
  - name: Add hosts
    lineinfile: dest=/etc/hosts regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="192.168.68.128 emr1"
 
  - name: Export Java home
    lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/hadoop-env.sh regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="export JAVA_HOME=/usr/java/jdk1.8.0_40"
  - shell: mkdir -p /app/hadoop/tmp
  - shell: chown -R hadoop:hadoop /app/hadoop/tmp
  - name: Edit core site
    lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/core-site.xml regexp="^\[\[ -s \\$HOME/\.pythonbrew" insertafter="<configuration>"     line="<property><name>hadoop.tmp.dir</name><value>/app/hadoop/tmp</value></property><property><name>fs.default.name</name><value>hdfs://localhost:9000</value></property>"
  - name: Edit HDFS site
    lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/hdfs-site.xml regexp="^\[\[ -s \\$HOME/\.pythonbrew" insertafter="<configuration>" line="<property><name>dfs.replication</name><value>1</value></property><property><name>dfs.name.dir</name><value>/home/hadoop/hadoop-2.6.0/hadoopdata/hdfs/namenode</value></property><property><name>dfs.data.dir</name><value>/home/hadoop/hadoop-2.6.0/hadoopdata/hdfs/datanode</value></property>"
  - name: edit mapred-site.xml
    lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/mapred-site.xml.template regexp="^\[\[ -s \\$HOME/\.pythonbrew" insertafter="<configuration>" line="<property><name>mapreduce.framework.name</name><value>yarn</value></property>"
  - name: Edit yarn-site.xml
    lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/yarn-site.xml regexp="^\[\[ -s \\$HOME/\.pythonbrew" insertafter="<configuration>" line="<property><name>yarn.nodemanager.aux-services</name><value>mapreduce_shuffle</value></property>"
  - shell: rm -Rf /app/hadoop/tmp/*
  - shell: chown -R hadoop:hadoop /home/hadoop/hadoop-2.6.0
  - shell: su - hadoop -c "hdfs namenode -format -force"
  - shell: su - hadoop -c "start-dfs.sh"
  - shell: su - hadoop -c "start-yarn.sh"

