---
- hosts: webservers
  user: root
  sudo: yes
  vars: 
    hadoop_home: /home/hadoop/hadoop-2.6.0
  tasks:
  - name: Configure Hadoop on Master Server Only
    lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/slaves regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="master"

  - lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/slaves regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="slave1"
  - lineinfile: dest=/home/hadoop/hadoop-2.6.0/etc/hadoop/slaves regexp="^\[\[ -s \\$HOME/\.pythonbrew" line="slave2"

  - shell: rm -Rf /app/hadoop/tmp/*

  - shell: chown -R hadoop:hadoop /home/hadoop/hadoop-2.6.0

  - shell: su - hadoop -c "hdfs namenode -format -force"

  - shell: su - hadoop -c "start-all.sh"
    ignore_errors: yes 
